name: Godot Linting

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  lint:
    name: Lint Godot Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gdtoolkit
      
      - name: Lint GDScript files
        run: |
          echo "Checking GDScript files for linting issues..."
          echo "=================================================="
          echo "When errors appear with 'class-definitions-order', please ensure you follow this order:"
          echo "1. Class/tool declarations"
          echo "2. Enums and constants (const VAR_NAME = value)"
          echo "3. Exported variables (@export var var_name = value)"
          echo "4. Public variables (var var_name = value)"
          echo "5. Private variables (var _var_name = value)"
          echo "6. Onready variables (@onready var var_name = $Node)"
          echo "7. Built-in virtual methods (func _ready(), _process(), etc.)"
          echo "8. Public methods (func method_name())"
          echo "9. Private methods (func _method_name())"
          echo "10. Signal callbacks (func _on_signal_name())"
          echo "=================================================="
          find foragewithme -name "*.gd" -type f -not -path "*/addons/*" -print0 | xargs -0 -I{} gdlint {} || true
          echo ""
      
      - name: Check file naming conventions
        run: |
          echo "Checking file naming conventions..."
          # Check for scene files (.tscn) using PascalCase
          find foragewithme -name "*.tscn" -type f -not -path "*/addons/*" | grep -v '[A-Z][a-zA-Z0-9]*\.tscn$' > .tscn_naming_violations.txt || true
          
          # Check for script files (.gd) using snake_case
          find foragewithme -name "*.gd" -type f -not -path "*/addons/*" | grep -v '[a-z][a-z0-9_]*\.gd$' > .gd_naming_violations.txt || true
          
          # Check for resource files (.tres) using snake_case
          find foragewithme -name "*.tres" -type f -not -path "*/addons/*" | grep -v '[a-z][a-z0-9_]*\.tres$' > .tres_naming_violations.txt || true
          
          # Display violations
          echo "Scene file (.tscn) naming violations (should be PascalCase):"
          cat .tscn_naming_violations.txt
          echo "Script file (.gd) naming violations (should be snake_case):"
          cat .gd_naming_violations.txt
          echo "Resource file (.tres) naming violations (should be snake_case):"
          cat .tres_naming_violations.txt
          
          # Check if any violations exist and fail accordingly
          if [ -s .tscn_naming_violations.txt ] || [ -s .gd_naming_violations.txt ] || [ -s .tres_naming_violations.txt ]; then
            echo "Error: File naming convention violations found!"
            exit 1
          else
            echo "Success: No file naming convention violations found."
          fi

      - name: Create custom gdlint.toml file
        run: |
          cat > gdlint.toml << 'EOF'
          # Linting rules for GDScript according to project standards
          
          # Formatting rules
          line_length = 100
          indent_size = 4
          
          # Naming rules
          function_name = "snake_case"
          variable_name = "snake_case"
          constant_name = "UPPER_SNAKE_CASE"
          class_name = "PascalCase"
          
          # Spacing rules
          class_definitions_per_file = 1
          empty_line_between_functions = true
          EOF
      
      - name: Run custom linting with configuration
        run: |
          echo "Running GDScript linting with custom configuration..."
          echo "=================================================="
          echo "Common linting errors and how to fix them:"
          echo ""
          echo "class-definitions-order:"
          echo "  - Description: Variable and method definitions appear in the wrong order"
          echo "  - Fix: Arrange your code following the standard GDScript structure (see above)"
          echo "  - Example: @onready variables should appear after regular variables"
          echo ""
          echo "expression-not-assigned:"
          echo "  - Description: Expression result unused"
          echo "  - Fix: Ensure the expression result is assigned or used appropriately"
          echo ""
          echo "unnecessary-pass:"
          echo "  - Description: Unnecessary 'pass' statement"
          echo "  - Fix: Remove 'pass' statements from blocks that have other code"
          echo ""
          echo "class-name-convention:"
          echo "  - Description: Class names should use PascalCase"
          echo "  - Fix: Rename your class to follow PascalCase (e.g., 'class_name MyClass')"
          echo ""
          echo "function-name-convention:"
          echo "  - Description: Function names should use snake_case"
          echo "  - Fix: Rename your function using snake_case (e.g., 'func my_function()')"
          echo "=================================================="
          find foragewithme -name "*.gd" -type f -not -path "*/addons/*" -print0 | xargs -0 -I{} gdlint --config gdlint.toml {} || true
          echo ""
      
      - name: Run comprehensive custom linting
        run: |
          echo "Running comprehensive custom linting..."
          echo "=================================================="
          echo "This custom linting step checks for project-specific standards."
          echo "If errors are found, please follow the guidelines in the project documentation."
          echo "=================================================="
          chmod +x .github/scripts/godot_custom_lint.py
          python .github/scripts/godot_custom_lint.py foragewithme
          echo ""
          
      - name: Summary
        run: |
          echo "==== Linting Summary ===="
          echo "The linting process checked for the following standards:"
          echo "1. Naming Conventions:"
          echo "   - Classes/Nodes: PascalCase"
          echo "   - Variables: snake_case"
          echo "   - Constants: UPPER_SNAKE_CASE"
          echo "   - Functions: snake_case"
          echo "   - Signals: snake_case"
          echo "   - Enum Values: UPPER_SNAKE_CASE"
          echo "2. File Naming:"
          echo "   - Scene Files (.tscn): PascalCase"
          echo "   - Script Files (.gd): snake_case" 
          echo "   - Resource Files (.tres): snake_case"
          echo "3. Code Formatting:"
          echo "   - 4 spaces for indentation"
          echo "   - Lines under 100 characters"
          echo "   - One empty line between functions"
          echo "   - Two empty lines between classes"
          echo "4. Script Structure Order:"
          echo "   - Class/tool declarations"
          echo "   - Enums and constants"
          echo "   - Exported variables"
          echo "   - Public variables"
          echo "   - Private variables"
          echo "   - Onready variables"
          echo "   - Built-in virtual methods"
          echo "   - Public methods"
          echo "   - Private methods"
          echo "   - Signal callbacks"
          echo ""
          echo "Note: Files in the 'addons' directory are excluded from linting"
